import numpy as np
def epipolar_line(a_x, a_y, a_z, b_x, b_y, b_z, bw_q, bx_q, by_q, bz_q, cent_x, cent_y, f, f_B, p_x, p_y, w_q_A, x_q_A, y_q_A, z_q_A):
	cent_img = np.zeros(16)
	cent_img[11] = (-f) # e0 ^ (e1 ^ e2)
	cent_img[12] = cent_y - p_y # e0 ^ (e1 ^ e3)
	cent_img[13] = (-(cent_x - p_x)) # e0 ^ (e2 ^ e3)
	rotor_A = np.zeros(16)
	rotor_A[9] = (-y_q_A) # e1 ^ e3
	translator_A = np.zeros(16)
	translator_A[5] = (-(a_x / 2.0)) # e0 ^ e1
	translator_A[6] = (-(a_y / 2.0)) # e0 ^ e2
	translator_A[7] = (-(a_z / 2.0)) # e0 ^ e3
	motor_A = np.zeros(16)
	motor_A[5] = translator_A[5] * w_q_A + (-(translator_A[6] * z_q_A)) + (-(translator_A[7] * rotor_A[9])) # e0 ^ e1
	motor_A[6] = translator_A[5] * z_q_A + translator_A[6] * w_q_A + (-(translator_A[7] * x_q_A)) # e0 ^ e2
	motor_A[7] = translator_A[5] * rotor_A[9] + translator_A[6] * x_q_A + translator_A[7] * w_q_A # e0 ^ e3
	motor_A[15] = translator_A[5] * x_q_A + (-(translator_A[6] * rotor_A[9])) + translator_A[7] * z_q_A # e0 ^ (e1 ^ (e2 ^ e3))
	cent_wcs_A = np.zeros(16)
	cent_wcs_A[11] = ((-(z_q_A * cent_img[11])) + (-(rotor_A[9] * cent_img[12])) + (-(x_q_A * cent_img[13])) + (-motor_A[15])) * (-z_q_A) + (-((-x_q_A) * (-motor_A[6]))) + rotor_A[9] * (-motor_A[5]) + (-((-z_q_A) * motor_A[15])) + (w_q_A * cent_img[11] + motor_A[7] + (-(rotor_A[9] * cent_img[13])) + x_q_A * cent_img[12]) * w_q_A + (-((w_q_A * cent_img[12] + (-motor_A[6]) + z_q_A * cent_img[13] + (-(x_q_A * cent_img[11]))) * (-x_q_A))) + (w_q_A * cent_img[13] + motor_A[5] + (-(z_q_A * cent_img[12])) + rotor_A[9] * cent_img[11]) * (-rotor_A[9]) + (-(w_q_A * (-motor_A[7]))) # e0 ^ (e1 ^ e2)
	cent_wcs_A[12] = ((-(z_q_A * cent_img[11])) + (-(rotor_A[9] * cent_img[12])) + (-(x_q_A * cent_img[13])) + (-motor_A[15])) * (-rotor_A[9]) + (-((-x_q_A) * (-motor_A[7]))) + rotor_A[9] * motor_A[15] + (-z_q_A) * (-motor_A[5]) + (w_q_A * cent_img[11] + motor_A[7] + (-(rotor_A[9] * cent_img[13])) + x_q_A * cent_img[12]) * (-x_q_A) + (w_q_A * cent_img[12] + (-motor_A[6]) + z_q_A * cent_img[13] + (-(x_q_A * cent_img[11]))) * w_q_A + (-((w_q_A * cent_img[13] + motor_A[5] + (-(z_q_A * cent_img[12])) + rotor_A[9] * cent_img[11]) * (-z_q_A))) + w_q_A * (-motor_A[6]) # e0 ^ (e1 ^ e3)
	cent_wcs_A[13] = ((-(z_q_A * cent_img[11])) + (-(rotor_A[9] * cent_img[12])) + (-(x_q_A * cent_img[13])) + (-motor_A[15])) * (-x_q_A) + (-((-x_q_A) * motor_A[15])) + (-(rotor_A[9] * (-motor_A[7]))) + (-z_q_A) * (-motor_A[6]) + (-((w_q_A * cent_img[11] + motor_A[7] + (-(rotor_A[9] * cent_img[13])) + x_q_A * cent_img[12]) * (-rotor_A[9]))) + (w_q_A * cent_img[12] + (-motor_A[6]) + z_q_A * cent_img[13] + (-(x_q_A * cent_img[11]))) * (-z_q_A) + (w_q_A * cent_img[13] + motor_A[5] + (-(z_q_A * cent_img[12])) + rotor_A[9] * cent_img[11]) * w_q_A + (-(w_q_A * (-motor_A[5]))) # e0 ^ (e2 ^ e3)
	cent_wcs_A[14] = (-x_q_A) * (-x_q_A) + (-(rotor_A[9] * (-rotor_A[9]))) + (-z_q_A) * (-z_q_A) + w_q_A * w_q_A # e1 ^ (e2 ^ e3)
	pos_A = np.zeros(16)
	pos_A[11] = (-a_z) # e0 ^ (e1 ^ e2)
	pos_A[13] = (-a_x) # e0 ^ (e2 ^ e3)
	pos_B = np.zeros(16)
	pos_B[11] = (-b_z) # e0 ^ (e1 ^ e2)
	pos_B[13] = (-b_x) # e0 ^ (e2 ^ e3)
	epipolar_plane = np.zeros(16)
	epipolar_plane[1] = ((-pos_A[13]) * cent_wcs_A[12] + (-(a_y * (-cent_wcs_A[13])))) * (-pos_B[11]) + (-(((-pos_A[13]) * (-cent_wcs_A[11]) + (-((-pos_A[11]) * (-cent_wcs_A[13])))) * b_y)) + (a_y * (-cent_wcs_A[11]) + (-((-pos_A[11]) * cent_wcs_A[12]))) * (-pos_B[13]) # e0
	epipolar_plane[2] = (-((cent_wcs_A[12] + (-(a_y * cent_wcs_A[14]))) * (-pos_B[11]) + (-(((-cent_wcs_A[11]) + (-((-pos_A[11]) * cent_wcs_A[14]))) * b_y)) + a_y * (-cent_wcs_A[11]) + (-((-pos_A[11]) * cent_wcs_A[12])))) # e1
	epipolar_plane[3] = ((-cent_wcs_A[13]) + (-((-pos_A[13]) * cent_wcs_A[14]))) * (-pos_B[11]) + (-(((-cent_wcs_A[11]) + (-((-pos_A[11]) * cent_wcs_A[14]))) * (-pos_B[13]))) + (-pos_A[13]) * (-cent_wcs_A[11]) + (-((-pos_A[11]) * (-cent_wcs_A[13]))) # e2
	epipolar_plane[4] = (-(((-cent_wcs_A[13]) + (-((-pos_A[13]) * cent_wcs_A[14]))) * b_y + (-((cent_wcs_A[12] + (-(a_y * cent_wcs_A[14]))) * (-pos_B[13]))) + (-pos_A[13]) * cent_wcs_A[12] + (-(a_y * (-cent_wcs_A[13]))))) # e3
	rotor_B = np.zeros(16)
	rotor_B[9] = (-by_q) # e1 ^ e3
	translator_B = np.zeros(16)
	translator_B[5] = (-(b_x / 2.0)) # e0 ^ e1
	translator_B[6] = (-(b_y / 2.0)) # e0 ^ e2
	translator_B[7] = (-(b_z / 2.0)) # e0 ^ e3
	motor_B = np.zeros(16)
	motor_B[5] = translator_B[5] * bw_q + (-(translator_B[6] * bz_q)) + (-(translator_B[7] * rotor_B[9])) # e0 ^ e1
	motor_B[6] = translator_B[5] * bz_q + translator_B[6] * bw_q + (-(translator_B[7] * bx_q)) # e0 ^ e2
	motor_B[7] = translator_B[5] * rotor_B[9] + translator_B[6] * bx_q + translator_B[7] * bw_q # e0 ^ e3
	motor_B[15] = translator_B[5] * bx_q + (-(translator_B[6] * rotor_B[9])) + translator_B[7] * bz_q # e0 ^ (e1 ^ (e2 ^ e3))
	plane_local_B = np.zeros(16)
	plane_local_B[1] = (-f_B) # e0
	image_plane_B = np.zeros(16)
	image_plane_B[1] = (bw_q * plane_local_B[1] + motor_B[7]) * bw_q + (-(rotor_B[9] * (-motor_B[5]))) + (-(bx_q * (-motor_B[6]))) + (-(bw_q * (-motor_B[7]))) + (-((bz_q * plane_local_B[1] + motor_B[15]) * (-bz_q))) + (-((motor_B[5] + rotor_B[9] * plane_local_B[1]) * (-rotor_B[9]))) + (-((motor_B[6] + bx_q * plane_local_B[1]) * (-bx_q))) + bz_q * motor_B[15] # e0
	image_plane_B[2] = rotor_B[9] * bw_q + (-(bx_q * (-bz_q))) + (-(bw_q * (-rotor_B[9]))) + (-(bz_q * (-bx_q))) # e1
	image_plane_B[3] = rotor_B[9] * (-bz_q) + bx_q * bw_q + (-(bw_q * (-bx_q))) + bz_q * (-rotor_B[9]) # e2
	image_plane_B[4] = rotor_B[9] * (-rotor_B[9]) + bx_q * (-bx_q) + bw_q * bw_q + (-(bz_q * (-bz_q))) # e3
	image_plane_B[11] = (bw_q * plane_local_B[1] + motor_B[7]) * (-bz_q) + (-(rotor_B[9] * (-motor_B[6]))) + bx_q * (-motor_B[5]) + (-(bw_q * motor_B[15])) + (bz_q * plane_local_B[1] + motor_B[15]) * bw_q + (-((motor_B[5] + rotor_B[9] * plane_local_B[1]) * (-bx_q))) + (motor_B[6] + bx_q * plane_local_B[1]) * (-rotor_B[9]) + (-(bz_q * (-motor_B[7]))) # e0 ^ (e1 ^ e2)
	image_plane_B[12] = (bw_q * plane_local_B[1] + motor_B[7]) * (-rotor_B[9]) + (-(rotor_B[9] * (-motor_B[7]))) + bx_q * motor_B[15] + bw_q * (-motor_B[5]) + (bz_q * plane_local_B[1] + motor_B[15]) * (-bx_q) + (motor_B[5] + rotor_B[9] * plane_local_B[1]) * bw_q + (-((motor_B[6] + bx_q * plane_local_B[1]) * (-bz_q))) + bz_q * (-motor_B[6]) # e0 ^ (e1 ^ e3)
	image_plane_B[13] = (bw_q * plane_local_B[1] + motor_B[7]) * (-bx_q) + (-(rotor_B[9] * motor_B[15])) + (-(bx_q * (-motor_B[7]))) + bw_q * (-motor_B[6]) + (-((bz_q * plane_local_B[1] + motor_B[15]) * (-rotor_B[9]))) + (motor_B[5] + rotor_B[9] * plane_local_B[1]) * (-bz_q) + (motor_B[6] + bx_q * plane_local_B[1]) * bw_q + (-(bz_q * (-motor_B[5]))) # e0 ^ (e2 ^ e3)
	image_plane_B[14] = rotor_B[9] * (-bx_q) + (-(bx_q * (-rotor_B[9]))) + bw_q * (-bz_q) + bz_q * bw_q # e1 ^ (e2 ^ e3)
	epipolar_line_B = np.zeros(16)
	epipolar_line_B[5] = image_plane_B[1] * epipolar_plane[2] + (-(image_plane_B[2] * epipolar_plane[1])) # e0 ^ e1
	epipolar_line_B[6] = image_plane_B[1] * epipolar_plane[3] + (-(image_plane_B[3] * epipolar_plane[1])) # e0 ^ e2
	epipolar_line_B[7] = image_plane_B[1] * epipolar_plane[4] + (-(image_plane_B[4] * epipolar_plane[1])) # e0 ^ e3
	epipolar_line_B[8] = image_plane_B[2] * epipolar_plane[3] + (-(image_plane_B[3] * epipolar_plane[2])) # e1 ^ e2
	epipolar_line_B[9] = image_plane_B[2] * epipolar_plane[4] + (-(image_plane_B[4] * epipolar_plane[2])) # e1 ^ e3
	epipolar_line_B[10] = image_plane_B[3] * epipolar_plane[4] + (-(image_plane_B[4] * epipolar_plane[3])) # e2 ^ e3
	epipolar_line_B[15] = image_plane_B[11] * epipolar_plane[4] + (-(image_plane_B[12] * epipolar_plane[3])) + image_plane_B[13] * epipolar_plane[2] + (-(image_plane_B[14] * epipolar_plane[1])) # e0 ^ (e1 ^ (e2 ^ e3))
	epipolar_line_px = np.zeros(16)
	epipolar_line_px[5] = ((-((-bz_q) * epipolar_line_B[8])) + (-((-rotor_B[9]) * epipolar_line_B[9])) + (-((-bx_q) * epipolar_line_B[10]))) * motor_B[5] + (bw_q * epipolar_line_B[5] + (-((-motor_B[6]) * epipolar_line_B[8])) + (-((-motor_B[7]) * epipolar_line_B[9])) + (-bz_q) * epipolar_line_B[6] + (-rotor_B[9]) * epipolar_line_B[7] + (-((-bx_q) * epipolar_line_B[15])) + (-(motor_B[15] * epipolar_line_B[10]))) * bw_q + (-((bw_q * epipolar_line_B[6] + (-motor_B[5]) * epipolar_line_B[8] + (-((-motor_B[7]) * epipolar_line_B[10])) + (-((-bz_q) * epipolar_line_B[5])) + (-rotor_B[9]) * epipolar_line_B[15] + (-bx_q) * epipolar_line_B[7] + motor_B[15] * epipolar_line_B[9]) * bz_q)) + (-((bw_q * epipolar_line_B[7] + (-motor_B[5]) * epipolar_line_B[9] + (-motor_B[6]) * epipolar_line_B[10] + (-((-bz_q) * epipolar_line_B[15])) + (-((-rotor_B[9]) * epipolar_line_B[5])) + (-((-bx_q) * epipolar_line_B[6])) + (-(motor_B[15] * epipolar_line_B[8]))) * rotor_B[9])) + (bw_q * epipolar_line_B[8] + (-((-rotor_B[9]) * epipolar_line_B[10])) + (-bx_q) * epipolar_line_B[9]) * motor_B[6] + (bw_q * epipolar_line_B[9] + (-bz_q) * epipolar_line_B[10] + (-((-bx_q) * epipolar_line_B[8]))) * motor_B[7] + (-((bw_q * epipolar_line_B[10] + (-((-bz_q) * epipolar_line_B[9])) + (-rotor_B[9]) * epipolar_line_B[8]) * motor_B[15])) + (-((bw_q * epipolar_line_B[15] + (-motor_B[5]) * epipolar_line_B[10] + (-((-motor_B[6]) * epipolar_line_B[9])) + (-motor_B[7]) * epipolar_line_B[8] + (-bz_q) * epipolar_line_B[7] + (-((-rotor_B[9]) * epipolar_line_B[6])) + (-bx_q) * epipolar_line_B[5]) * bx_q)) # e0 ^ e1
	epipolar_line_px[6] = ((-((-bz_q) * epipolar_line_B[8])) + (-((-rotor_B[9]) * epipolar_line_B[9])) + (-((-bx_q) * epipolar_line_B[10]))) * motor_B[6] + (bw_q * epipolar_line_B[5] + (-((-motor_B[6]) * epipolar_line_B[8])) + (-((-motor_B[7]) * epipolar_line_B[9])) + (-bz_q) * epipolar_line_B[6] + (-rotor_B[9]) * epipolar_line_B[7] + (-((-bx_q) * epipolar_line_B[15])) + (-(motor_B[15] * epipolar_line_B[10]))) * bz_q + (bw_q * epipolar_line_B[6] + (-motor_B[5]) * epipolar_line_B[8] + (-((-motor_B[7]) * epipolar_line_B[10])) + (-((-bz_q) * epipolar_line_B[5])) + (-rotor_B[9]) * epipolar_line_B[15] + (-bx_q) * epipolar_line_B[7] + motor_B[15] * epipolar_line_B[9]) * bw_q + (-((bw_q * epipolar_line_B[7] + (-motor_B[5]) * epipolar_line_B[9] + (-motor_B[6]) * epipolar_line_B[10] + (-((-bz_q) * epipolar_line_B[15])) + (-((-rotor_B[9]) * epipolar_line_B[5])) + (-((-bx_q) * epipolar_line_B[6])) + (-(motor_B[15] * epipolar_line_B[8]))) * bx_q)) + (-((bw_q * epipolar_line_B[8] + (-((-rotor_B[9]) * epipolar_line_B[10])) + (-bx_q) * epipolar_line_B[9]) * motor_B[5])) + (bw_q * epipolar_line_B[9] + (-bz_q) * epipolar_line_B[10] + (-((-bx_q) * epipolar_line_B[8]))) * motor_B[15] + (bw_q * epipolar_line_B[10] + (-((-bz_q) * epipolar_line_B[9])) + (-rotor_B[9]) * epipolar_line_B[8]) * motor_B[7] + (bw_q * epipolar_line_B[15] + (-motor_B[5]) * epipolar_line_B[10] + (-((-motor_B[6]) * epipolar_line_B[9])) + (-motor_B[7]) * epipolar_line_B[8] + (-bz_q) * epipolar_line_B[7] + (-((-rotor_B[9]) * epipolar_line_B[6])) + (-bx_q) * epipolar_line_B[5]) * rotor_B[9] # e0 ^ e2
	epipolar_line_px[7] = ((-((-bz_q) * epipolar_line_B[8])) + (-((-rotor_B[9]) * epipolar_line_B[9])) + (-((-bx_q) * epipolar_line_B[10]))) * motor_B[7] + (bw_q * epipolar_line_B[5] + (-((-motor_B[6]) * epipolar_line_B[8])) + (-((-motor_B[7]) * epipolar_line_B[9])) + (-bz_q) * epipolar_line_B[6] + (-rotor_B[9]) * epipolar_line_B[7] + (-((-bx_q) * epipolar_line_B[15])) + (-(motor_B[15] * epipolar_line_B[10]))) * rotor_B[9] + (bw_q * epipolar_line_B[6] + (-motor_B[5]) * epipolar_line_B[8] + (-((-motor_B[7]) * epipolar_line_B[10])) + (-((-bz_q) * epipolar_line_B[5])) + (-rotor_B[9]) * epipolar_line_B[15] + (-bx_q) * epipolar_line_B[7] + motor_B[15] * epipolar_line_B[9]) * bx_q + (bw_q * epipolar_line_B[7] + (-motor_B[5]) * epipolar_line_B[9] + (-motor_B[6]) * epipolar_line_B[10] + (-((-bz_q) * epipolar_line_B[15])) + (-((-rotor_B[9]) * epipolar_line_B[5])) + (-((-bx_q) * epipolar_line_B[6])) + (-(motor_B[15] * epipolar_line_B[8]))) * bw_q + (-((bw_q * epipolar_line_B[8] + (-((-rotor_B[9]) * epipolar_line_B[10])) + (-bx_q) * epipolar_line_B[9]) * motor_B[15])) + (-((bw_q * epipolar_line_B[9] + (-bz_q) * epipolar_line_B[10] + (-((-bx_q) * epipolar_line_B[8]))) * motor_B[5])) + (-((bw_q * epipolar_line_B[10] + (-((-bz_q) * epipolar_line_B[9])) + (-rotor_B[9]) * epipolar_line_B[8]) * motor_B[6])) + (-((bw_q * epipolar_line_B[15] + (-motor_B[5]) * epipolar_line_B[10] + (-((-motor_B[6]) * epipolar_line_B[9])) + (-motor_B[7]) * epipolar_line_B[8] + (-bz_q) * epipolar_line_B[7] + (-((-rotor_B[9]) * epipolar_line_B[6])) + (-bx_q) * epipolar_line_B[5]) * bz_q)) # e0 ^ e3
	epipolar_line_px[8] = ((-((-bz_q) * epipolar_line_B[8])) + (-((-rotor_B[9]) * epipolar_line_B[9])) + (-((-bx_q) * epipolar_line_B[10]))) * bz_q + (bw_q * epipolar_line_B[8] + (-((-rotor_B[9]) * epipolar_line_B[10])) + (-bx_q) * epipolar_line_B[9]) * bw_q + (-((bw_q * epipolar_line_B[9] + (-bz_q) * epipolar_line_B[10] + (-((-bx_q) * epipolar_line_B[8]))) * bx_q)) + (bw_q * epipolar_line_B[10] + (-((-bz_q) * epipolar_line_B[9])) + (-rotor_B[9]) * epipolar_line_B[8]) * rotor_B[9] # e1 ^ e2
	epipolar_line_px[9] = ((-((-bz_q) * epipolar_line_B[8])) + (-((-rotor_B[9]) * epipolar_line_B[9])) + (-((-bx_q) * epipolar_line_B[10]))) * rotor_B[9] + (bw_q * epipolar_line_B[8] + (-((-rotor_B[9]) * epipolar_line_B[10])) + (-bx_q) * epipolar_line_B[9]) * bx_q + (bw_q * epipolar_line_B[9] + (-bz_q) * epipolar_line_B[10] + (-((-bx_q) * epipolar_line_B[8]))) * bw_q + (-((bw_q * epipolar_line_B[10] + (-((-bz_q) * epipolar_line_B[9])) + (-rotor_B[9]) * epipolar_line_B[8]) * bz_q)) # e1 ^ e3
	epipolar_line_px[10] = ((-((-bz_q) * epipolar_line_B[8])) + (-((-rotor_B[9]) * epipolar_line_B[9])) + (-((-bx_q) * epipolar_line_B[10]))) * bx_q + (-((bw_q * epipolar_line_B[8] + (-((-rotor_B[9]) * epipolar_line_B[10])) + (-bx_q) * epipolar_line_B[9]) * rotor_B[9])) + (bw_q * epipolar_line_B[9] + (-bz_q) * epipolar_line_B[10] + (-((-bx_q) * epipolar_line_B[8]))) * bz_q + (bw_q * epipolar_line_B[10] + (-((-bz_q) * epipolar_line_B[9])) + (-rotor_B[9]) * epipolar_line_B[8]) * bw_q # e2 ^ e3
	line_e01 = np.zeros(16)
	line_e01[0] = epipolar_line_px[5] # 1.0
	line_e02 = np.zeros(16)
	line_e02[0] = epipolar_line_px[6] # 1.0
	line_e03 = np.zeros(16)
	line_e03[0] = epipolar_line_px[7] # 1.0
	line_e12 = np.zeros(16)
	line_e12[0] = epipolar_line_px[8] # 1.0
	line_e13 = np.zeros(16)
	line_e13[0] = epipolar_line_px[9] # 1.0
	line_e23 = np.zeros(16)
	line_e23[0] = epipolar_line_px[10] # 1.0
	return line_e01, line_e02, line_e03, line_e12, line_e13, line_e23
